using System;
using System.Collections.ObjectModel;
using System.ComponentModel;

namespace HTML2PDF.ViewModels
{
    internal class MainWindowViewModel : ViewModelBase, INotifyPropertyChanged
    {
        public Func<PdfConverterViewModel> PdfConverterViewModelFactory;
        private PdfConverterViewModel _CurrentViewModel;

        private string _LoadingStatusLabel;

        public MainWindowViewModel(Func<PdfConverterViewModel> PdfConverterViewModelFactory) : base()
        {
            this.PdfConverterViewModelFactory = PdfConverterViewModelFactory;
            CurrentViewModel = PdfConverterViewModelFactory();
        }

        public MainWindowViewModel()
        {
            Initialize();
        }

        public PdfConverterViewModel CurrentViewModel
        {
            get => _CurrentViewModel; set
            {
                _CurrentViewModel = value;
                NotifyPropertyChanged();
            }
        }

        /// <summary>
        /// User-facing status message
        /// </summary>
        public string ErrorStatusLabel { get => _LoadingStatusLabel; set { _LoadingStatusLabel = value; NotifyPropertyChanged(); } }

        /// <summary>
        /// List of status messages generated by conversion process.
        /// </summary>
        public ObservableCollection<string> ListConversionStatusUpdates { get; set; } = new ObservableCollection<string>();

        public void Initialize()
        {
            ListConversionStatusUpdates = new ObservableCollection<string>();
        }
    }
}